var lpc={
	init:function(obj){
		switch(obj.t)
		{
			case'news':
				showNews();
				break;
			case'logo':
				logoChange(obj.d);
				break;
			case'bg':
				$('body').css('background-image','url('+obj.d+')');
				break;
			case'nick':
				msg.nick.init(obj.d[0],obj.d[1],obj.d[2],obj.d[3],obj.d[4],obj.d[5],obj.d[6]);
				break;
			case'musicAdd':
				musName=obj.d.name;
				musAddr=obj.d.addr;
				musId=obj.d.id;
				musicAdd();
				break;
			case'musicDel':
				musicDel(obj.d);
				break;
			case'smilesRenew':
				smilesRenew(obj.d);
				break;
			case'sound':
				sound.src=obj.d;
				break;
			case'delMsg':
				delMsg(obj.d);
				break;
			case'bday':
				//var bday=document.getElementById("bday");if(bday){bday.innerHTML="'.addslashes($bday).'";}
				$('#bday').html(obj.d);
				break;
			case'reload':
				document.location.replace(obj.d);
				break;
			case'punish':
				punish.execute(obj.d);
				break;
			case'exit':
				ui.exit(obj.d[0],obj.d[1],obj.d[2]);
				break;
			case'status':
				inputFormSetStatus(obj.d[0],obj.d[1],obj.d[2],obj.d[3],obj.d[4]);
				break;
			case'bonus':
				$('#bonus').html(obj.d);
				break;
		}
	}
};